### ISSUE TITLE
Examples of markdown constructors

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#14]
Add a new section to this repo https://standards-hub.github.io/Generate_documentation_Nuxt/ e.g. "Markdown Constructors"
that contains a list of examples from https://content.nuxtjs.org/advanced 
Single document with multiple subsections.

**Comment by anthonyaveiga** [comment]
Already solved here #8

**Comment by jpradocueva** [comment]
completed.
