### ISSUE TITLE
Update section titles by removing angular brackets (<)

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#15]
In the example below, some section titles have been listed with angular brackets (<) and <=(>).
Please remove these angular brackets and leave the section as a normal section H2 title

![image](https://user-images.githubusercontent.com/3258579/125332855-66d90000-e2fe-11eb-8a75-d53af2f6aa9e.png)

**Comment by anthonyaveiga** [comment]
changes added in 036770089465c862b9ea666eb54d84843a094977

**Comment by jpradocueva** [comment]
The section titles should start with a capital, e.g. Alert, List

**Comment by anthonyaveiga** [comment]
Solved: aeb6747446d1f4a311fec561df234609d3b603ff

**Comment by jpradocueva** [comment]
Good, this issue is addressed.
