### ISSUE TITLE
Add two explanatory sentences to each constructor

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#17]
For instance, make it clear to the reader which part is how it is displayed and how the constructor is defined in markdown.

See an example in https://github.com/standards-hub/markdown_constructors/pull/16/files

**Comment by anthonyaveiga** [comment]
solved: a0acd1a74b71146b78644ed48b832b1d47024b88

**Comment by anthonyaveiga** [comment]
also here 793a34d38e65ba2d7934bd732de831951ab99b38 and here 6644480f49422a19bbaa03906ef8496cf5bc3695

**Comment by jpradocueva** [comment]
The followings changes are needed:
The comment is marked as title

![image](https://user-images.githubusercontent.com/3258579/125527049-cf972edb-ed20-4762-a59f-1551a4468606.png)

The order of the comments is incorrect:
![image](https://user-images.githubusercontent.com/3258579/125527182-00081673-962c-4b30-915f-f88502767b5f.png)

In this screenshot, "alert" should be in capital Alert.
What does it mean
"Props ..." is this needed? I don't really understand the need for this content
![image](https://user-images.githubusercontent.com/3258579/125534855-9e340c07-3b62-4690-9ca5-cf67b053a867.png)

**Comment by jpradocueva** [comment]
In general, I see that the following sections: Alert, List, Code Block, Code Sanbox (make sure the titles look like this, without e.g., code-block) have a subsection called "Props".
The content listed under this subsection doesn't make sense to me, I don't understand what is the intention or value to show it, for example:
![image](https://user-images.githubusercontent.com/3258579/125535484-b732ba1e-1ba3-4daf-bc24-cb11c7236fee.png)

Why do we need it? If it is not clear to you either, then I suggest deleting it.

**Comment by anthonyaveiga** [comment]
All these updates solved here: fba28608ee5363e4c4e0f086725b8046ce05f7d6

**Comment by jpradocueva** [comment]
Completed thanks!
