### ISSUE TITLE
Strikethrough and Task List are listed as header level 3

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#18]
Is there any particular reason why Strikethrough and Task List is listed as header 3 rather than header 2?
https://standards-hub.github.io/markdown_constructors/#strikethrough

**Comment by anthonyaveiga** [comment]
changes added in 32360ea76828b9f9f53c26d91c62bc0e28cc7755

**Comment by jpradocueva** [comment]
completed
