### ISSUE TITLE
First display constructor then explain how it is written

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#19]
Ensure that we follow the same order in each constructor. 
First show how it is displayed, then indicate how it is written in markdown.

In this case, https://standards-hub.github.io/markdown_constructors/#task-list
 the order seems reverser, first is indicated how it is written and then explained how it is displayed.

**Comment by anthonyaveiga** [comment]
changes added in a0acd1a74b71146b78644ed48b832b1d47024b88

**Comment by jpradocueva** [comment]
There is something strange in how the Fence Code is written in markdown, the block in angular brackets is not listed. Is this correct?

**Comment by jpradocueva** [comment]
I suggest changing the expression from `'info'` `alert` to `Info-Alert`
Same for:
`Success-Alert`, `Warning-Alert` and `Danger-Alert`

**Comment by anthonyaveiga** [comment]
@jpradocueva 

> There is something strange in how the Fence Code is written in markdown, the block in angular brackets is not listed. Is this correct?

is written that way because it is not possible to write backticks (```) inside a code block. It would look like this:
![image](https://user-images.githubusercontent.com/45562713/125810972-6f5ee254-e05d-45eb-bbbd-4bbcaa538274.png)

Also, the solution proposed here: https://www.markdownguide.org/basic-syntax/#escaping-backticks doesn't help much because nuxt renders it this way:
![image](https://user-images.githubusercontent.com/45562713/125811789-acbbf49c-4b6a-4631-8ff3-df9ef8e36c7f.png)

**Comment by anthonyaveiga** [comment]
Solved. I used ~~~ instead of ````. See 54746ec164c566e39315b5999433e05f6310884c

**Comment by anthonyaveiga** [comment]
> I suggest changing the expression from `'info'` `alert` to `Info-Alert`
> Same for:
> `Success-Alert`, `Warning-Alert` and `Danger-Alert`

Done. See 3620c21c9867cd7bb0da084591595f145ff4c7da

**Comment by jpradocueva** [comment]
Completed, thanks
