### ISSUE TITLE
Alert order and how it is written down 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#20]
The order in this displayed doesn't seem to be aligned with what is written in the example.
I am suggesting writing the content in markdown next to each display, in this case, it is clear how it should be written down in order to obtain a different alert.

![image](https://user-images.githubusercontent.com/3258579/125335194-2038d500-e301-11eb-9d40-2fe8585dd723.png)

**Comment by anthonyaveiga** [comment]
changes added in 83bfb67c14f60a1b3670e1a81062841b554ca7b9

**Comment by jpradocueva** [comment]
done!
