### ISSUE TITLE
Add folder and file name to the code example

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#24]
What markdown expression we need to write in order to list the folder and file name of the file. See highlight below.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/3258579/125713097-586113cf-ca30-45e9-8cf5-f87828a82448.png">

**Comment by anthonyaveiga** [comment]
@jpradocueva 
In order to do this, the following syntax is used:

~~~
```[/folder/filename.filetype]

Code here!
```
~~~

Filename and folder inside square brackets

**Comment by jpradocueva** [comment]
@anthonyaveiga that is a very useful constructor.
