### ISSUE TITLE
Expose the version of the application that we build in the footer

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#25]
Is possible too expose the version of the application listed in the `package.json` file see highlight below, in the footer of the page. See also below

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/3258579/125714189-1b456516-868d-4bf4-9e50-dd85fc41c6c9.png">

Example of an application exposing the version of the application in the footer.

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/3258579/125714443-b15486ab-6e43-497c-af5e-b5479bef9660.png">

**Comment by anthonyaveiga** [comment]
solved: #28

**Comment by jpradocueva** [comment]
Completed.
