### ISSUE TITLE
How to make URLs inside of alert boxes better highliged 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#26]
In this example, the URLs inside of the alert boxes appear in bold and in color.
Is that richness provided via CSS or is anything in the alert box that can be configured?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/3258579/125716037-747253f7-b0d8-4aa2-8bc7-603ad7e1bc02.png">

**Comment by anthonyaveiga** [comment]
@jpradocueva 
In that example, those styles are provided by CSS. See:
![image](https://user-images.githubusercontent.com/45562713/125824521-9b2ad974-e764-49d1-a5ac-ee61f2fe15fe.png)

Nuxt comes with default Vue.js components that can be used in markdown content. The "alert" component does not have any properties to change the way links are displayed. These are the default styles of Nuxt.

**Comment by jpradocueva** [comment]
@anthonyaveiga thanks!
