### ISSUE TITLE
How to maintain list of "Releases" 

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#5]
What we need to do in order to maintain the list of "Releases"

![image](https://user-images.githubusercontent.com/3258579/124533194-b97a5f80-ddc6-11eb-89e2-4dbd3d972e3d.png)

**Comment by anthonyaveiga** [comment]
In order to display the release page, it is only needed to add the repository in the settings.json file.

**Comment by jpradocueva** [comment]
The `settings.json` file can be found here https://github.com/standards-hub/markdown_constructors/blob/main/content/settings.json

**Comment by jpradocueva** [comment]
Now we need to identify the module/file that contains the code that once executed show the releases.

**Comment by jpradocueva** [comment]
The Release function appears when the GitHub link has been added `settings.json` file
