### ISSUE TITLE
Continue describing how to write markdown constructors

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#8]
PR #7 shows how to write markdown constructors. 
@anthonyaveiga please review PR #7 and merge it. Then continue describing the rest of the markdown constructors using the same methodology: 
1. show the constructors how is displayed in markdown, then 
2. write below how it is written in markdown using   (``` md) please edit this comment to view constructors  (```)

**Comment by anthonyaveiga** [comment]
solved: 5fa89551c24b2ce5cccf2d14d9256847ea2d2ec6

**Comment by anthonyaveiga** [comment]
solved here 5fa89551c24b2ce5cccf2d14d9256847ea2d2ec6 and here #12

**Comment by anthonyaveiga** [comment]
other changes added in #13

**Comment by jpradocueva** [comment]
Completed
