### ISSUE TITLE
Find out how Nuxt read the content from Release

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/markdown_constructors#9]
For example this release https://github.com/nuxt/content/releases/tag/v1.14.0 it seems that appears directly in https://standards-hub.github.io/markdown_constructors/releases/

**Comment by anthonyaveiga** [comment]
this issue has already been addressed in #5

**Comment by jpradocueva** [comment]
Location of the `settings.json` file is https://github.com/standards-hub/markdown_constructors/blob/main/content/settings.json

**Comment by jpradocueva** [comment]
@anthonyaveiga remember that an issue should be closed by the person that raised it.
